"""Modifying chunk, embedding field in chunks table

Revision ID: 25e29a7c3893
Revises: 5042391788aa
Create Date: 2026-06-14 00:38:51.871791

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "25e29a7c3893"
down_revision: str | Sequence[str] | None = "5042391788aa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
