"""Modifying filename field in chunks table

Revision ID: 2b4f52e47063
Revises: 98f550162f98
Create Date: 2026-06-13 23:47:53.260457

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "2b4f52e47063"
down_revision: str | Sequence[str] | None = "98f550162f98"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
