"""add local_vault_path to vaults

Revision ID: 30fa1cba4c93
Revises: 3e06ccd61ba2
Create Date: 2026-09-06 15:51:43.922701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30fa1cba4c93'
down_revision: Union[str, Sequence[str], None] = '3e06ccd61ba2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vaults', sa.Column('local_vault_path', sa.String(), nullable=True))
    op.drop_column('vaults', 'local_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vaults', sa.Column('local_path', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.drop_column('vaults', 'local_vault_path')
    # ### end Alembic commands ###
