"""add_local_path_to_vaults

Revision ID: 3e06ccd61ba2
Revises: 7434d8dcdd10
Create Date: 2026-09-06 15:41:43.391600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e06ccd61ba2'
down_revision: Union[str, Sequence[str], None] = '7434d8dcdd10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vaults', sa.Column('local_path', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vaults', 'local_path')
    # ### end Alembic commands ###
