"""Modifying chunk, embedding field in chunks table

Revision ID: 5042391788aa
Revises: 2b4f52e47063
Create Date: 2026-06-13 23:51:09.779167

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "5042391788aa"
down_revision: str | Sequence[str] | None = "2b4f52e47063"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
