"""checking if alembic adds tables

Revision ID: 612c6cd25879
Revises: 25e29a7c3893
Create Date: 2026-06-14 00:45:35.459750

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "612c6cd25879"
down_revision: str | Sequence[str] | None = "25e29a7c3893"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
