"""Updating database schema to use job_id

Revision ID: f22ed5c3636a
Revises: c05091141b10
Create Date: 2026-08-29 00:30:28.345271

"""

from collections.abc import Sequence

import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f22ed5c3636a"
down_revision: str | Sequence[str] | None = "c05091141b10"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chunks", sa.Column("job_id", sa.String(), nullable=False))
    op.alter_column(
        "chunks", "embedding", existing_type=Vector(dim=768), nullable=False
    )
    op.drop_index(op.f("ix_chunks_filename"), table_name="chunks")
    op.drop_index(op.f("ix_chunks_id"), table_name="chunks")
    op.create_index(op.f("ix_chunks_job_id"), "chunks", ["job_id"], unique=False)
    op.drop_column("chunks", "filename")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chunks",
        sa.Column("filename", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_index(op.f("ix_chunks_job_id"), table_name="chunks")
    op.create_index(op.f("ix_chunks_id"), "chunks", ["id"], unique=False)
    op.create_index(op.f("ix_chunks_filename"), "chunks", ["filename"], unique=False)
    op.alter_column("chunks", "embedding", existing_type=Vector(dim=768), nullable=True)
    op.drop_column("chunks", "job_id")
    # ### end Alembic commands ###
