"""Added Jobs tables and updated the chunks table

Revision ID: f71b1ad8c2fb
Revises: b090fc560abd
Create Date: 2026-09-02 03:00:34.261864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f71b1ad8c2fb'
down_revision: Union[str, Sequence[str], None] = 'b090fc560abd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('source_filename', sa.String(), nullable=False))
    op.add_column('chunks', sa.Column('chunk_tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', chunk_text)", persisted=True), nullable=True))
    op.create_index('ix_chunks_tsv', 'chunks', ['chunk_tsv'], unique=False, postgresql_using='gin')
    op.add_column('jobs', sa.Column('total_files', sa.Integer(), nullable=False))
    op.add_column('jobs', sa.Column('succeeded', sa.Integer(), nullable=False))
    op.add_column('jobs', sa.Column('failed_files', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'failed_files')
    op.drop_column('jobs', 'succeeded')
    op.drop_column('jobs', 'total_files')
    op.drop_index('ix_chunks_tsv', table_name='chunks', postgresql_using='gin')
    op.drop_column('chunks', 'chunk_tsv')
    op.drop_column('chunks', 'source_filename')
    # ### end Alembic commands ###
